version: '3'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi_app:latest
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - UVICORN_LOG_LEVEL=info

  corsight:
    ports:
      - "8080:8080"